SELECT
    P.PRODUCT_ID AS PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(P.PRICE * O.AMOUNT) AS TOTAL_SALES # 총매출 (문제 한번 더 확인)
FROM FOOD_PRODUCT AS P
JOIN FOOD_ORDER AS O
    ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY PRODUCT_ID
# HAVING PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;