SELECT
    YEAR(o.SALES_DATE) AS YEAR,
    MONTH(o.SALES_DATE) AS MONTH,
    i.GENDER,
    COUNT(DISTINCT o.USER_ID) AS USERS # 중복제거 후 집계
FROM USER_INFO AS i
JOIN ONLINE_SALE AS o # Join 문법 주의
    ON o.USER_ID = i.USER_ID
WHERE i.GENDER IS NOT NULL # "이때, 성별 정보가 없는 경우 결과 제외"
GROUP BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE), i.GENDER
ORDER BY YEAR ASC, MONTH ASC, i.GENDER ASC;