SELECT 
    COUNT(*) AS FISH_COUNT, # NULL값이 있으니 COUNT(*)로 집계
    n.FISH_NAME
FROM FISH_INFO AS i
JOIN FISH_NAME_INFO AS n
    ON i.FISH_TYPE = n.FISH_TYPE # mapping key
GROUP BY n.FISH_NAME
ORDER BY FISH_COUNT DESC;