SELECT QUARTER, COUNT(*) AS ECOLI_COUNT
FROM # 서브쿼리에서 가져옴
(
SELECT 
    CASE
        WHEN QUARTER(DIFFERENTIATION_DATE) = 1 THEN '1Q' # 분기 추출 및 foramting
        WHEN QUARTER(DIFFERENTIATION_DATE) = 2 THEN '2Q'
        WHEN QUARTER(DIFFERENTIATION_DATE) = 3 THEN '3Q'
        WHEN QUARTER(DIFFERENTIATION_DATE) = 4 THEN '4Q'
    END AS QUARTER
FROM ECOLI_DATA
) AS t # 서브쿼리가 먼저 실행
GROUP BY QUARTER # 가져온걸 groupby & sorted
ORDER BY QUARTER ASC;