-- 코드를 입력하세요
SELECT
    I.REST_ID,
    I.REST_NAME,
    I.FOOD_TYPE,
    I.FAVORITES,
    I.ADDRESS,
    ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS I
JOIN REST_REVIEW AS R
    ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE "서울%" -- "서울특별시%" 로 하면 오답 ADDRESS 값에 "서울시 ~" 로 돼 있는 값들도 있음
GROUP BY 
    I.REST_ID
ORDER BY SCORE DESC, I.FAVORITES DESC;