SELECT 
    ANIMAL_TYPE,
    COUNT(ANIMAL_TYPE) AS COUNT # 문법 주의 ex: COUNT 집계 후 반드시 GROUP BY
FROM ANIMAL_INS
WHERE ANIMAL_TYPE = 'Cat' or ANIMAL_TYPE = 'Dog' # Or 연산 주의
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE ASC;