SELECT
    d.DEPT_ID,
    d.DEPT_NAME_EN,
    ROUND(AVG(e.SAL), 0) AS AVG_SAL
FROM HR_DEPARTMENT AS d
JOIN HR_EMPLOYEES AS e # JOIN 문법 복습하기 (자꾸 까먹음) 'JOIN TABLE_NAME AS ~ ON ~ = '
on d.DEPT_ID = e.DEPT_ID
GROUP BY DEPT_ID
ORDER BY AVG_SAL DESC;