SELECT MCDP_CD AS '진료과코드',
    COUNT(DISTINCT PT_NO) AS '5월예약건수' # 중복 제거 후 COUNT
FROM APPOINTMENT
WHERE LEFT(APNT_YMD, 10) BETWEEN '2022-05-01' AND '2022-05-31' # 날짜 format parsing 후 추출
GROUP BY MCDP_CD
ORDER BY 5월예약건수 ASC, 진료과코드 ASC;
