# 7월 아이스크림 총 주문량과 상반기의 아이스크림 총 주문량을 더한 값이 큰 순서대로 상위 3개의 맛을 조회하는 SQL 문을 작성
# 기본키: FLAVOR
# 외래키: SHIPMENT_ID

SELECT 
     F.FLAVOR
FROM FIRST_HALF AS F
JOIN JULY AS J
    ON F.FLAVOR = J.FLAVOR
GROUP BY F.SHIPMENT_ID
ORDER BY SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC
LIMIT 3;